In [1]:
import numpy as np

#### Creating an array

In [2]:
# 0D
arr0= np.array(42)
print(arr0)

42


In [3]:
# 1D
arr1= np.array([1, 2, 3, 4, 5])
print(arr1)

[1 2 3 4 5]


In [4]:
# 2D
arr2= np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [5]:
# 3D (3*3 for this example)
arr3= np.array([[[1, 2, 3],[4, 5, 6]], [[7, 8, 9],[10, 11, 12]]])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


#### Check number of dimension

In [6]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


### Higher dimension array (ndmin)

In [7]:
# Creating an array with 5 dimensions
arr5 = np.array([1, 2, 3, 4, 5], ndmin=5)
print(arr5)
print("Number of dimension is ", arr5.ndim)

[[[[[1 2 3 4 5]]]]]
Number of dimension is  5


## Array indexing

In [8]:
arr = np.array([1, 2, 3, 4, 5])

print("first item ", arr[0])
print("last item ", arr[-1])
print("third item ", arr[2])

first item  1
last item  5
third item  3


In [9]:
arr2 = np.array([[1, 2, 3],[4, 5, 6]])
print(arr2[1, 2]) #because of indexing (2, 3)

6


In [10]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3[0, 1, 1]) #second element in the second row of first matrix

5


#### Negative indexing

In [11]:
arr= np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, -2]) # second last element of second row

9


### Array slicing

#### [start:end:step]

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[1:5]) #from index 1 to 4
print(arr[:4]) #from index 0 to 3
print(arr[4:]) #from index 4 to end

[2 3 4 5]
[1 2 3 4]
[5 6 7 8 9]


#### Negative slicing

In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[-3:-1]) #third to last element(7) to less than last element

[7 8]


#### Step

In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2]) #from index 1 to 4 with a step size of 2

[2 4]


#### slicing 2-D array

In [15]:
arr2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr2[1, 2:5]) #index second to fourth in 2nd row

[ 8  9 10]


In [16]:
print(arr2[0:2, 2]) #second index from both rows

[3 8]


### data type

In [17]:
arr= np.array([1, 2, 3, 4, 5])
print(arr.dtype)

int64


In [18]:
arr= np.array([1, "a", True])
print(arr.dtype)

<U21


#### creating array with defined data type

In [19]:
arr= np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


#### converting data type on existing arrays

In [20]:
arr= np.array([1.0, 2.2, 3.0, 4.0])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3 4]
int32


#### similar

In [21]:
newarr2 = arr.astype(int)
print(newarr2)
print(newarr2.dtype)

[1 2 3 4]
int64


In [22]:
newarr3 = arr.astype(bool)
print(newarr3)
print(newarr3.dtype)

[ True  True  True  True]
bool


## Copy and View

#### change made to copied array doesnot effect the original array
#### change made to viewed array effects the original array

In [23]:
arr= np.array([1, 2, 3, 4])
x = arr.copy()
y = arr.view()

x[1] =40
y[0] = 22
print(x)
print(y)
print(arr)

[ 1 40  3  4]
[22  2  3  4]
[22  2  3  4]


## Shape and reshape

In [24]:
arr =np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print("shape of array is: ", arr.shape)

[[[[[1 2 3 4]]]]]
shape of array is:  (1, 1, 1, 1, 4)


In [25]:
# Reshaping from 1D to 2d
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3) #The outermost dimension will have 4 arrays, each with 3 elements
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [26]:
# Reshape from 1D to 3D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2) #The outermost dimension will have 2 arrays with each array having 3 arrays of 2 size
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


#### check if returned array is a copy or view

In [27]:
print(newarr.base)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


#### It returns original array, so it is a view

## Unknown dimension
#### we are allowed to have one unknown dimension
#### pass -1 to the unknown value, numpy will calculate the number

In [28]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Flattening the arrays

#### we can use reshape(-1) to do this

In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


### Iterating

In [30]:
# 1D array
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [31]:
# 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [32]:
# 3D array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [33]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


#### nditer for iterating

In [34]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


#### iterating with different data types

In [35]:
arr = np.array([1, 2, 3])
for x in np.nditer(arr, flags=['buffered'], op_dtypes=["S"]):
    print(x)

b'1'
b'2'
b'3'


#### with different step sizes

In [36]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


### Enumerated iteration

#### using ndenumerate()

#### means mentioning sequence with index

In [37]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


### Joining array

#### concatenate() function

In [39]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [42]:
# Joining two 2D arrays along row(axix=1)
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


### joining arrays using stack function

In [44]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


## Stacking along Rows

In [45]:
arr= np.hstack((arr1, arr2))
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


## Stacking along Columns

In [46]:
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Stacking along height(depth)

In [47]:
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [48]:
### Splitting array

In [50]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)  # newarr is an array of arrays obtained by dividing 'arr' into 3 parts

[array([1, 2]), array([3, 4]), array([5, 6])]


In [51]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr) 

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [52]:
### splitting 2D array

In [56]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr[0], "\n")
print(newarr[1], "\n")
print(newarr[2], "\n")

[[1 2]
 [3 4]] 

[[5 6]
 [7 8]] 

[[ 9 10]
 [11 12]] 



In [57]:
#### alternative is to use hsplit (the opposite of hstack)

In [58]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [59]:
### Searching arrays

In [60]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6]),)


In [61]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


#### searchsorted() finds the index where a specified number is appropriate to insert

In [64]:
arr = np.array([6, 7, 9, 13])

x = np.searchsorted(arr, 8)

print(x)

2


In [66]:
#where should 7 be inserted from right to keep the array sorted
x = np.searchsorted(arr, 7, side='right') 
print(x)

2


### sorting

In [68]:
arr = np.array([0, 8, 4, 2, 10, 1])
print(np.sort(arr))

[ 0  1  2  4  8 10]


#### sorting a 2D array

In [70]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


#### Filtering array

In [72]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr) # only values corresponding to 'True' are displayed

[41 43]


In [73]:
# creating a filter array

arr=np.array([40, 44, 45, 10, 8, 20, 88, 100, 98, 42])

filter_array = []

#suppose we want to eliminate values below 40

for element in arr:
    if element >= 40:
        filter_array.append(True)
    else:
        filter_array.append(False)

newarr = arr[filter_array]
print(filter_array)
print(newarr)


[True, True, True, False, False, False, True, True, True, True]
[ 40  44  45  88 100  98  42]


#### creating filter directly from array

In [76]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_array = arr%2 == 0  #filtering even numbers

newarr = arr[filter_array]

print(filter_array)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
